main:
  name: ecaps_cifar_10
  seed: 1
  cuda: true
  verbosity: 0
arch:
  type: FinalCapsNet
  args:
    use_background_class: true
loss:
  type: TotalLoss
  args:
    m_pos: 0.9
    m_neg: 0.1
    lambda_: 0.5
    recon_factor: 0.0005
data_loader:
  type: Cifar10DataLoader
  args:
    data_dir: ../
    batch_size: 16
    shuffle: true
    validation_split: 0.1
    num_workers: 1
    augmentation: none
    data_fraction: 0.33
optimizer:
  type: Adam
  args:
    lr: 0.0005
lr_scheduler:
  type: ExponentialLR
  args:
    gamma: 0.98
metrics:
- accuracy
trainer:
  epochs: 100
  log_step: 1700
  save_dir: saved/
  save_period: 10
  verbosity: 0
  monitor: min val_loss
  early_stop: -5
  tensorboard: true
logger:
  version: 1
  disable_existing_loggers: false
  formatters:
    brief:
      format: '%(message)s'
    precise:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: brief
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: precise
      filename: info.log
      maxBytes: 1000000.0
      backupCount: 5
      encoding: utf8
  root:
    level: INFO
    handlers:
    - console
    - file
