main:
  name: 'ecaps'
arch:
  type: 'FinalCapsNet'
  args: # see model/model.py
    use_background_class: True
loss:
  type: 'TotalLoss'
  args: # see model/losses.py
    m_pos: 0.9
    m_neg: 0.1
    lambda_: 0.5
    recon_factor: 5.e-4
