main:
  name: 'deit_tiny'
arch:
  type: 'TimmClassifier'
  args:
    model_name: 'deit_tiny_patch16_224'
    num_classes: 10
    pretrained: False
    patch_size: 4
    img_size: 32
loss:
  type: 'ClassificationLoss'
  args: {}
